(
SELECT 
c.COUNTRY_ID,
c.COUNTRY_NAME
FROM COUNTRIES c
LEFT JOIN LOCATIONS l ON l.COUNTRY_ID = c.COUNTRY_ID
LEFT JOIN DEPARTMENTS d ON d.LOCATION_ID = l.LOCATION_ID
)
MINUS
(
SELECT 
c.COUNTRY_ID,
c.COUNTRY_NAME
FROM COUNTRIES c
LEFT JOIN LOCATIONS l ON l.COUNTRY_ID = c.COUNTRY_ID
LEFT JOIN DEPARTMENTS d ON d.LOCATION_ID = l.LOCATION_ID
GROUP BY c.COUNTRY_NAME,c.COUNTRY_ID--l.LOCATION_ID
HAVING COUNT(l.LOCATION_ID) >= 1
)
;



Select * from departments;

select * from locations;


