INSERT INTO MY_EMPLOYEE (ID,LAST_NAME,FIRST_NAME,USERID,SALARY) 
VALUES (&ID,'&&LAST_NAME','&&FIRST_NAME',LOWER(concat(SUBSTR('&FIRST_NAME',1,1),SUBSTR('&LAST_NAME',1,7))),&SALARY);

UNDEFINE LAST_NAME;
UNDEFINE FIRST_NAME;

--Q 26 
select * from my_employee;
