SELECT
  e1.DEPARTMENT_ID AS "DEPARTMENT",
  e1.LAST_NAME AS "EMPLOYEE",
  e2.LAST_NAME AS "COLLEAGUE"
FROM EMPLOYEES e1
JOIN EMPLOYEES e2 ON e1.DEPARTMENT_ID = e2.DEPARTMENT_ID
ORDER BY e1.LAST_NAME, e1.DEPARTMENT_ID;
