SELECT
e.LAST_NAME,
e.JOB_ID,
d.DEPARTMENT_ID,
d.DEPARTMENT_NAME
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON l.LOCATION_ID = d.LOCATION_ID
WHERE l.CITY = 'Toronto'
;