SELECT
  DISTINCT JOB_ID AS "Job",
  DECODE(DEPARTMENT_ID, 20,ROUND(AVG(SALARY),0), null) AS "Dept 20",
  DECODE(DEPARTMENT_ID, 50,ROUND(AVG(SALARY),0), null) AS "Dept 50",
  DECODE(DEPARTMENT_ID, 80,ROUND(AVG(SALARY),0), null) AS "Dept 80",
  DECODE(DEPARTMENT_ID, 90,ROUND(AVG(SALARY),0), null) AS "Dept 90",
  DECODE(JOB_ID,JOB_ID,SUM(SALARY),null) AS "Total"           
FROM EMPLOYEES
WHERE DEPARTMENT_ID is not null
GROUP BY DEPARTMENT_ID, JOB_ID
;
